### ISSUE TITLE
请问基础和每天投入时间

### ISSUE THREAD

**Issue by l11x0m7** [luckyzhz/Software-Designer#1]
你好，我想请教下您学习前的基础，以及每天平均投入时间，谢谢~

**Comment by luckyzhz** [comment]
在软考前，我主要有简单的 Python 编程基础。
备考期间，平均可能每天投入 2~3 小时。关键是专心，持之以恒，学习期间不要玩手机。
如果之前完全没接触过计算机知识，可以在本教程的基础上多学一个月。
祝你今年顺利通过考试，good luck 😁

**Comment by zhuniao** [comment]
视频链接是2018年的，2022年考的话，这个视频会不会有点老。

**Comment by luckyzhz** [comment]
官方教材至今依然是 2018 年的，你可以理解为考纲至今依然没变。所以使用 2018 年的教学视频是 OK 的。

**Comment by qiufeihong2018** [comment]
前端开发者，如何做下午的题目呢
